name: Build site

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build artefact
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.1
          run_install: true

      - name: Run build
        run: pnpm build
